<?php
/**
 * mutation-bwach.php — Mutationstest für den Batteriewächter.
 *
 * Verändert je Durchlauf EINE Entscheidungsstelle im Modul (Grenzwert, Vorzeichen,
 * Ausschluss …) in einer temporären Kopie und lässt den Prüfstand laufen. Ein
 * Mutant gilt als „getötet“, wenn der Prüfstand fehlschlägt. Überlebt einer, hat
 * der Prüfstand dort eine Lücke (oder die Mutation ist wirkungslos).
 *
 * Aufruf:   php .tools/mutation-bwach.php
 * Rückgabe: 0 = alle Mutanten getötet, 1 = mindestens einer überlebt
 */

$root = dirname(__DIR__);
$src  = $root . '/Batteriewaechter';

// [Datei, Suchtext, Ersatz, Beschreibung]
// Bewusst NICHT aufgenommen: die Grenzfälle „Spannung genau am Kurvenende“ (die Zwischenrechnung liefert dort dasselbe)
// und Wegfall des Kurzschlusses in truncateBytes (gleiches Ergebnis).
// Bewusst NICHT aufgenommen (gleichwertige Mutanten der Gruppen-Regeln): Wegfall der Prüfung auf ein unbekanntes Kriterium (das Gerät hat dafür keinen Wert, es passt nie), „Gruppe überschreiben“ und „kritisch setzen“ ohne Blick auf die eigene Einstellung (eigenes „Ereignismelder“ und eigenes „kritisch“ sind schon der Zielwert).
// Bewusst NICHT aufgenommen (gleichwertige Mutanten, Verhalten bleibt identisch): Wegfall der Namenssperre
// „ladung“ (die Namenserkennung lässt „Batterieladung“ ohnehin nicht zu) und Wegfall von „$found === null“
// im Tick (LastDiscoveryTs = 0 löst dieselbe Suche aus).
$mutations = [
    ['BWACHLogik.php', '$pct <= $emptyThr ? self::ST_EMPTY', '$pct < $emptyThr ? self::ST_EMPTY', 'Grenze „leer“ ≤ → <'],
    ['BWACHLogik.php', '$pct < $lowThr ? self::ST_LOW', '$pct <= $lowThr ? self::ST_LOW', 'Grenze „schwach“ < → ≤'],
    ['BWACHLogik.php', '$lifeAge > $stillSec) {', '$lifeAge >= $stillSec) {', 'Funkstille > → ≥'],
    ['BWACHLogik.php', '$valueAge > $oldDays * 86400', '$valueAge >= $oldDays * 86400', 'Wertalter > → ≥'],
    ['BWACHLogik.php', '$score += 100', '$score += 50', 'Kritisch-Zuschlag'],
    ['BWACHLogik.php', '($flagLow && $pct >= $lowThr)', '($flagLow && $pct > $lowThr)', 'Widerspruch: ≥ → >'],
    ['BWACHLogik.php', '(!$flagLow && $pct <= $emptyThr)', '(!$flagLow && $pct < $emptyThr)', 'Widerspruch leer: ≤ → <'],
    ['BWACHLogik.php', '$status = $flagUpdated > $pctUpdated ? $stFlag : $stPct;', '$status = $flagUpdated > $pctUpdated ? $stPct : $stFlag;', 'Widerspruch: älteres statt neueres Signal'],
    ['BWACHLogik.php', '$status = self::worse($stPct, $stFlag);', '$status = $stPct;', 'Kritisch: schlechtere Aussage entfällt'],
    ['BWACHLogik.php', '!empty($sig[\'flag\'][\'reversed\']) ? !(bool)$sig[\'flag\'][\'value\']', '!empty($sig[\'flag\'][\'reversed\']) ? (bool)$sig[\'flag\'][\'value\']', 'umgekehrtes Flag nicht umgekehrt'],
    ['BWACHLogik.php', '(float)$sig[\'percent\'][\'value\'] * (float)($sig[\'percent\'][\'scale\'] ?? 1.0)', '(float)$sig[\'percent\'][\'value\']', 'Matter-Skala entfällt'],
    ['BWACHLogik.php', 'schwächste|niedrigste', 'niedrigste', 'Sammelwert „schwächste“ entfällt'],
    ['BWACHLogik.php', 'if (in_array(mb_strtolower((string)$v[\'moduleName\']), $excludedModules, true)) {', 'if (false) {', 'Modulausschluss aus'],
    ['BWACHLogik.php', 'if (!$v[\'parentIsInstance\']) {', 'if (false) {', 'Ausschluss „keine Geräteinstanz“ aus'],
    ['BWACHLogik.php', 'if ($s[\'basis\'] === self::BASIS_NAME && !$nameSearch) {', 'if (false) {', 'Namensvorschlag wird sofort aufgenommen'],
    ['BWACHLogik.php', "\$profile === '~Battery.Reversed'", "\$profile === '~Battery.ReversedX'", 'Profil ~Battery.Reversed nicht erkannt'],
    ['BWACHLogik.php', "if (\$funk === 'still') { \$score = max(\$score, 600); }", "if (\$funk === 'still') { \$score = max(\$score, 100); }", 'Dringlichkeit Funkstille zu niedrig'],
    ['BWACHLogik.php', "if (\$status === self::ST_UNKNOWN) { \$score = max(\$score, 200); }", '', 'Dringlichkeit „unbekannt“ entfällt'],
    ['BWACHLogik.php', 'empty($p[\'ignoreAge\'])', 'true', 'Altersprüfung nie abschaltbar'],
    ['BWACHLogik.php', '$group === self::GROUP_EVENT ? ($p[\'stillDaysEvent\'] ?? 30) : ($p[\'stillDays\'] ?? 7)', '($p[\'stillDays\'] ?? 7)', 'Ereignismelder-Gruppe wirkungslos'],
    ['BWACHLogik.php', '$aggregateInstances[(int)$v[\'parentId\']] = true;', '', 'Sammelgerät-Regel (Raum-Flag) entfällt'],
    ['BWACHLogik.php', 'if (count($list) < 2 || !empty($d[\'merged\'])) {', 'if (true) {', 'Mehrere Sensoren einer Instanz werden nicht geteilt'],
    ['module.php', 'if ((int)($var[\'VariableAction\'] ?? 0) > 0 || (int)($var[\'VariableCustomAction\'] ?? 0) > 0) {', 'if (false) {', 'Variablen mit Aktion zählen als Lebenszeichen'],
    // --- Meilenstein 2: Meldungslogik
    ['BWACHMeldung.php', "if (\$now - \$s['notified'] >= \$interval) {", "if (\$now - \$s['notified'] > \$interval) {", 'Erinnerung: ≥ → >'],
    ['BWACHMeldung.php', '$isNew = count(array_diff($probs, $s[\'probs\'])) > 0;', '$isNew = false;', 'Neuer Befund wird nie als neu erkannt'],
    ['BWACHMeldung.php', '$quiet = $quietNow && !($ignoreQuiet && !empty($c[\'critical\']));', '$quiet = $quietNow;', 'Kritische Geräte durchbrechen die Ruhezeit nicht'],
    ['BWACHMeldung.php', '$quiet = $quietNow && !($ignoreQuiet && !empty($c[\'critical\']));', '$quiet = false;', 'Ruhezeit wirkungslos'],
    ['BWACHMeldung.php', 'if ($now >= (int)$s[\'snooze\'] && !$quiet) {', 'if (!$quiet) {', 'Zurückstellen wirkungslos'],
    ['BWACHMeldung.php', "&& \$now - (int)\$s['since'] >= \$escHours * 3600) {", "&& \$now - (int)\$s['since'] > \$escHours * 3600) {", 'Eskalation: ≥ → >'],
    ['BWACHMeldung.php', '!$s[\'esc\'] && $s[\'notified\'] > 0', '$s[\'notified\'] > 0', 'Eskalation wiederholt sich'],
    ['BWACHMeldung.php', '} elseif ($now - $s[\'gone\'] >= $clearHours * 3600 && $now >= (int)$s[\'snooze\']) {', '} elseif ($now - $s[\'gone\'] >= 0) {', 'Karenzzeit für wackelnde Werte entfällt'],
    ['BWACHMeldung.php', 'return $fromHour < $toHour ? ($h >= $fromHour && $h < $toHour) : ($h >= $fromHour || $h < $toHour);', 'return $fromHour < $toHour ? ($h >= $fromHour && $h <= $toHour) : ($h >= $fromHour || $h <= $toHour);', 'Ruhezeit-Ende einschließlich'],
    ['BWACHMeldung.php', 'if (!$enabled || $fromHour === $toHour) {', 'if (!$enabled) {', 'Ruhezeit mit gleicher Start-/Endstunde'],
    ['BWACHMeldung.php', "\$cur['p'] - \$prev['p'] >= \$jumpPct", "\$cur['p'] - \$prev['p'] > \$jumpPct", 'Wechselerkennung: ≥ → >'],
    ['BWACHMeldung.php', "\$prev['f'] === true && \$cur['f'] === false", "\$prev['f'] === true", 'Flag-Wechsel ohne „jetzt ok“'],
    ['BWACHMeldung.php', "abs(\$entry['t'] - \$e['t']) < self::DIARY_DEDUPE_DAYS * 86400", "abs(\$entry['t'] - \$e['t']) <= self::DIARY_DEDUPE_DAYS * 86400", 'Tagebuch-Doppelte: < → ≤'],
    ['BWACHMeldung.php', '$e[\'key\'] === $entry[\'key\'] && ', '', 'Tagebuch fasst verschiedene Geräte zusammen'],
    ['BWACHMeldung.php', 'if (count($diary) > self::DIARY_CAP) {', 'if (false) {', 'Tagebuch unbegrenzt'],
    ['BWACHMeldung.php', "(int)date('G', \$now) < \$hour", "(int)date('G', \$now) <= \$hour", 'Wochenbericht: Stunde ≥ → >'],
    ['BWACHMeldung.php', 'if ($key === $lastKey) {', 'if (false) {', 'Wochenbericht mehrfach pro Woche'],
    ['BWACHMeldung.php', 'if ($n > 5) {', 'if ($n > 6) {', 'Bündelung: „und N weitere“ zu spät'],
    ['BWACHMeldung.php', 'if ($bytes + $cb > $maxBytes) {', 'if ($bytes + $cb >= $maxBytes) {', 'Byte-Kürzung zu knapp'],
    ['BWACHMeldung.php', 'self::REPLACE_GRACE_DAYS * 86400', '0', 'Wartezeit nach „getauscht“ entfällt'],
    ['BWACHMeldung.php', "\$title = \$n === 1 ? '🔔 Erinnerung'", "\$title = \$n === 1 ? '🔔 Erinnerung: ' . \$first['name']", 'Titel mit Gerätenamen sprengt 32 Byte'],
    // --- Meilenstein 2: Modul
    ['module.php', "if (!\$this->ReadPropertyBoolean('NotificationsActive')) {\n            return;\n        }", '', 'Meldungen laufen auch bei „aus“'],
    ['module.php', "\$state[\$k]['notified'] = (int)(\$old[\$k]['notified'] ?? 0);", '', 'Fehlgeschlagene Zustellung wird als gemeldet verbucht'],
    ['module.php', "return \$chosen ? array_intersect_key(\$all, \$chosen) : \$all;", 'return $all;', 'Push-Auswahl wirkungslos'],
    ['module.php', "|| isset(\$retired[(string)\$key])) {", ") {", 'Außer-Betrieb-Geräte werden weiter überwacht'],
    ['module.php', "'neu' => \$normal, 'erinnerung' => \$normal, 'eskalation' => \$esc", "'neu' => \$normal, 'erinnerung' => \$normal, 'eskalation' => \$normal", 'Eskalation nutzt den normalen Weg'],
    ['module.php', "if (\$this->deliver(\$d['title'], \$d['text'], \$d['sound'], \$channels) > 0) {", "if (true) {\n            \$this->deliver(\$d['title'], \$d['text'], \$d['sound'], \$channels);", 'Wochenbericht gilt auch bei Fehlschlag als gesendet'],
    ['module.php', "BWACHMeldung::truncateBytes(\$title, 32), BWACHMeldung::truncateBytes(\$text, 256), 'Alert'", "\$title, \$text, 'Alert'", 'Kachel-Push ohne Byte-Kürzung'],
    ['module.php', "unset(\$state[\$key]);\n                \$changed = true;", "\$changed = true;", 'Wechsel erledigt den alten Befund nicht'],
    ['module.php', "if (\$prev === null || \$prev['p'] !== \$cur['p'] || \$prev['f'] !== \$cur['f']) {", "if (\$prev === null) {", 'Zuletzt-gesehen wird nie aktualisiert'],
    ['module.php', "IPS_SetHidden(\$id, true);", '', 'Zustandsvariablen bleiben sichtbar'],
    // --- Meilenstein 3: Kachel
    ['module.php', "} elseif (is_array(\$d) && isset(\$d['key'], \$d['action'])) {", "} elseif (true) {\n                \$d = \$d ?: ['key' => '', 'action' => ''];", 'Ungültige Kachel-Anfrage wird nicht abgefangen'],
    ['module.php', "if (!\$this->ReadPropertyBoolean('TileAllowAck')) {", "if (false) {", 'Quittieren aus der Kachel nicht abschaltbar'],
    ['module.php', "JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS", "JSON_UNESCAPED_UNICODE", 'Gerätename kann die Kachel aufbrechen'],
    ['module.php', "\$now - (int)\$meta['ack']['t'] <= 30", "true", 'Rückmeldung bleibt ewig stehen'],
    ['module.php', "if (\$want !== '' && strpos(\$reason, \$want) === 0) {", "if (false) {", 'Unterzeile zeigt nie den Hauptbefund'],
    ['BWACHLogik.php', "preg_replace('/ Tage\$/', ' Tagen', \$s)", "\$s", 'Dativ „seit 16 Tagen“ entfällt'],
    // --- 0.3.1: Fehlerursache beim Mailversand
    ['BWACHMeldung.php', "strpos(\$h, 'login denied') !== false || ", "", 'Login denied wird nicht erkannt'],
    ['BWACHMeldung.php', "strpos(\$h, 'timed out') !== false || strpos(\$h, 'timeout') !== false", "false", 'Zeitüberschreitung wird nicht erkannt'],
    ['BWACHMeldung.php', "if (\$raw === '') {", "if (false) {", 'Leere Meldung ohne ehrlichen Hinweis'],
    ['module.php', "restore_error_handler();", "", 'Fehler-Handler bleibt hängen'],
    ['module.php', "\$warnings[] = (string)\$str;", "", 'Warnungen des SMTP-Moduls werden nicht gesammelt'],
    ['module.php', "'⚠️ nicht gesendet — ' . \$this->lastMailError", "'⚠️ nicht gesendet'", 'Testmeldung ohne Ursache'],
    ['module.php', "IPS_LogMessage('Batteriewächter', 'E-Mail-Versand fehlgeschlagen: ' . \$this->lastMailError);", "", 'Ursache nicht im Meldungslog'],
    ['module.php', "\$this->UpdateFormField('NotifyStatus', 'caption', \$out);", "", 'Testmeldung frischt die Statuszeile nicht auf'],
    // --- 0.4.0: Zelltypen, Prognose, Einkauf, Statistik
    ['BWACHZelle.php', 'if ($v > $top * 1.12 || $v < $low * 0.6) {', 'if (false) {', 'Spannung, die nicht zum Zelltyp passt, wird umgerechnet'],
    ['BWACHZelle.php', "\$volt / \$cells", "\$volt", 'Zellenzahl wird ignoriert'],
    ['BWACHPrognose.php', 'if ($n < self::FORECAST_MIN_POINTS || $span < self::FORECAST_MIN_SPAN) {', 'if ($n < 2) {', 'Prognose schon mit 2 Punkten'],
    ['BWACHPrognose.php', '$span < self::FORECAST_MIN_SPAN', '$span < 0', 'Prognose ohne Mindestzeitraum'],
    ['BWACHPrognose.php', 'if ($distinct < self::FORECAST_MIN_DISTINCT) {', 'if (false) {', 'Prognose aus groben Stufen'],
    ['BWACHPrognose.php', 'if ($slope >= self::NO_DISCHARGE_SLOPE) {', 'if (false) {', 'Keine-Entladung-Erkennung entfällt'],
    ['BWACHPrognose.php', 'if ($r2 >= 0.85 && $span >= 60 * 86400 && $n >= 8) {', 'if (true) {', 'Immer hohe Sicherheit'],
    ['BWACHPrognose.php', '} elseif ($r2 >= 0.6 && $span >= 30 * 86400) {', '} elseif (true) {', 'Immer mindestens mittlere Sicherheit'],
    ['BWACHPrognose.php', "if (\$series[\$i][1] - \$series[\$i - 1][1] >= \$jump) {", "if (\$series[\$i][1] - \$series[\$i - 1][1] > \$jump) {", 'Wechselsprung: ≥ → >'],
    ['BWACHPrognose.php', "return array_slice(\$series, \$start);", "return \$series;", 'Alter Abschnitt vor dem Wechsel zählt mit'],
    ['BWACHPrognose.php', 'if (abs($pct - $last[1]) < self::HISTORY_MIN_DELTA && $t - $last[0] < self::HISTORY_MIN_GAP) {', 'if (false) {', 'Verlauf speichert jeden Wert'],
    ['BWACHPrognose.php', 'if ($t <= $last[0]) {', 'if (false) {', 'Verlauf nimmt Zeit rückwärts an'],
    ['BWACHPrognose.php', 'if (count($series) > self::HISTORY_CAP) {', 'if (false) {', 'Verlauf unbegrenzt'],
    ['BWACHPrognose.php', '$soon = $i[\'days\'] !== null && $i[\'days\'] <= $horizonDays;', '$soon = $i[\'days\'] !== null && $i[\'days\'] < $horizonDays;', 'Einkauf: Horizont ≤ → <'],
    ['BWACHPrognose.php', "if (in_array(\$i['status'], ['leer', 'schwach'], true) || \$soon || !empty(\$i['preventive'])) {", "if (\$soon || !empty(\$i['preventive'])) {", 'Einkauf ignoriert akut schwache Geräte'],
    ['BWACHPrognose.php', "\$count[\$label] = (\$count[\$label] ?? 0) + max(1, (int)\$i['cells']);", "\$count[\$label] = (\$count[\$label] ?? 0) + 1;", 'Einkauf zählt Zellen je Gerät nicht'],
    ['BWACHPrognose.php', "\$t = max(\$now, \$t);", "", 'Tauschrunde darf in der Vergangenheit liegen'],
    ['BWACHPrognose.php', "- \$marginDays * 86400;", ";", 'Tauschrunde ohne Reserve'],
    ['BWACHPrognose.php', "if (count(\$gaps) < self::GAPS_MIN) {", "if (false) {", 'Gelernte Schwelle schon bei wenigen Beobachtungen'],
    ['BWACHPrognose.php', "max(6 * 3600, min(\$default, 3 * \$p90))", "min(\$default, 3 * \$p90)", 'Gelernte Schwelle ohne Untergrenze'],
    ['BWACHPrognose.php', "max(6 * 3600, min(\$default, 3 * \$p90))", "max(6 * 3600, 3 * \$p90)", 'Gelernte Schwelle über der eingestellten'],
    ['BWACHPrognose.php', "\$obs['gaps'] = array_slice(\$obs['gaps'], -self::GAPS_CAP);", "", 'Abstände unbegrenzt'],
    ['BWACHPrognose.php', "if (\$obs['last'] > 0 && \$life > \$obs['last']) {", "if (\$life > 0) {", 'Erste Beobachtung erzeugt einen Abstand'],
    ['BWACHLogik.php', "if (\$orphanDays > 0 && \$lifeAge > \$orphanDays * 86400) {", "if (\$orphanDays > 0 && \$lifeAge > 0) {", 'Verwaist-Vorschlag sofort'],
    ['BWACHLogik.php', "\$stillSec  = isset(\$p['stillSec']) && (int)\$p['stillSec'] > 0 ? (int)\$p['stillSec'] : \$stillDays * 86400;", "\$stillSec  = \$stillDays * 86400;", 'Gelernte Schwelle wirkungslos'],
    ['module.php', "in_array(\$f['confidence'], ['hoch', 'mittel'], true) && \$f['days'] <= \$this->ReadPropertyInteger('SoonDays')", "\$f['days'] <= \$this->ReadPropertyInteger('SoonDays')", '„Bald leer“ auch bei geringer Sicherheit'],
    ['module.php', "\$f['days'] <= \$this->ReadPropertyInteger('SoonDays')", "\$f['days'] < 0", '„Bald leer“ nie'],
    ['module.php', "\$stillSec < \$defaultStill ? \$stillSec : 0", "0", 'Gelernte Schwelle kommt nicht an'],
    ['module.php', "if (\$series) {\n                \$hist[\$key] = \$series;\n            }", "\$hist[\$key] = \$series;", 'Leere Verläufe werden gespeichert'],
    ['BWACHMeldung.php', "if (!empty(\$r['soon'])) {\n            \$p[] = self::PROB_SOON;\n        }", "", '„Bald leer“ löst keine Meldung aus'],
    // --- 0.5.0: Gleichartige, Funkqualität, Kälte, Abfrage, Übernahme
    ['BWACHPrognose.php', 'if (count($members) < $minGroup) {', 'if (false) {', 'Vergleich auch in zu kleinen Gruppen'],
    ['BWACHPrognose.php', 'if ($rate >= $factor * $med && $rate >= $minRate) {', 'if ($rate > $factor * $med && $rate >= $minRate) {', 'Gleichartige: ≥ → >'],
    ['BWACHPrognose.php', 'if ($rate >= $factor * $med && $rate >= $minRate) {', 'if ($rate >= $factor * $med) {', 'Gleichartige: Mindestrate entfällt'],
    ['BWACHPrognose.php', 'if ($r[\'rate\'] > 0) {', 'if (true) {', 'Gleichartige: Geräte ohne Entladung zählen mit'],
    ['BWACHPrognose.php', "\$c0 === null || \$c1 === null || \$t1 - \$t0 < 2 * 86400 || \$p1 - \$p0 >= \$jump", "\$t1 - \$t0 < 2 * 86400 || \$p1 - \$p0 >= \$jump", 'Kälte: Abschnitte ohne Temperatur zählen'],
    ['BWACHPrognose.php', "\$c0 === null || \$c1 === null || \$t1 - \$t0 < 2 * 86400 || \$p1 - \$p0 >= \$jump", "\$c0 === null || \$c1 === null || \$p1 - \$p0 >= \$jump", 'Kälte: zu kurze Abschnitte zählen'],
    ['BWACHPrognose.php', "\$c0 === null || \$c1 === null || \$t1 - \$t0 < 2 * 86400 || \$p1 - \$p0 >= \$jump", "\$c0 === null || \$c1 === null || \$t1 - \$t0 < 2 * 86400", 'Kälte: Batteriewechsel zählt als Abschnitt'],
    ['BWACHPrognose.php', "if ((\$c0 + \$c1) / 2 < \$below) {", "if ((\$c0 + \$c1) / 2 <= \$below) {", 'Kälte: Grenze < → ≤'],
    ['BWACHPrognose.php', "if (count(\$cold) >= self::COLD_MIN_INTERVALS && count(\$warm) >= self::COLD_MIN_INTERVALS) {", "if (count(\$cold) >= 1 && count(\$warm) >= 1) {", 'Kälte: schon mit einem Abschnitt je Seite'],
    ['BWACHPrognose.php', "if (count(\$ratios) < self::COLD_MIN_DEVICES) {", "if (count(\$ratios) < 1) {", 'Kälte: schon mit einem Gerät'],
    ['BWACHPrognose.php', "\$base['text'] = \$f >= 1.2", "\$base['text'] = \$f >= 0.1", 'Kälte: jeder Faktor gilt als deutlich'],
    ['BWACHLogik.php', "\$level = \$value < 50 ? 'schwach' : (\$value < 120 ? 'mittel' : 'gut');", "\$level = \$value < 50 ? 'schwach' : 'gut';", 'Funkqualität ohne Stufe „mittel“'],
    ['BWACHLogik.php', "\$level = \$value >= -70 ? 'gut' : (\$value >= -85 ? 'mittel' : 'schwach');", "\$level = \$value >= -70 ? 'gut' : (\$value >= -85 ? 'gut' : 'schwach');", 'RSSI: „mittel“ fehlt'],
    ['BWACHLogik.php', "if (\$smtp > 0 && \$instanceExists(\$smtp)) {", "if (\$smtp > 0) {", 'Übernahme trägt nicht vorhandene SMTP-Instanz ein'],
    ['BWACHLogik.php', "if (!empty(\$cfg['BatterieBenachrichtigungCBOX']) && (\$push || \$mail)) {", "if (!empty(\$cfg['BatterieBenachrichtigungCBOX'])) {", 'Übernahme schaltet Meldungen ohne Zustellweg ein'],
    ['module.php', "\$this->UpdateFormField(\$field, \$field === 'PushTargets' ? 'values' : 'value', \$value);", "IPS_SetProperty(\$this->InstanceID, \$field, \$value);", 'Übernahme speichert still in die Eigenschaften'],
    ['module.php', "if (!\$row['pollOn'] || \$fn === null || (!\$old && !\$still)) {", "if (\$fn === null || (!\$old && !\$still)) {", 'Abfrage auch bei ausgeschaltetem Gerät'],
    ['module.php', "\$fn = self::POLL_FUNCTIONS[\$row['module']] ?? null;", "\$fn = self::POLL_FUNCTIONS[\$row['module']] ?? 'ZW_RequestStatus';", 'Abfrage auch an anderen Systemen'],
    ['module.php', "\$old   = \$age !== null && \$age > \$after;", "\$old   = \$age !== null && \$age > 0;", 'Abfrage unabhängig vom Alter des Werts'],
    ['module.php', "if (isset(\$state[\$key]) && \$now - (int)\$state[\$key]['t'] < \$every) {", "if (false) {", 'Abfrage ohne Mindestabstand'],
    ['module.php', "} elseif (\$now - \$t > (self::POLL_WAIT[\$row['module']] ?? 14 * 86400)) {", "} elseif (false) {", 'Keine Antwort wird nie festgestellt'],
    ['module.php', "\$state[\$key] = ['t' => \$now, 'ans' => null, 'miss' => \$miss, 'why'", "\$state[\$key] = ['t' => \$now, 'ans' => null, 'miss' => 0, 'why'", 'Unbeantworteter Stand geht bei neuer Anfrage verloren'],
    ['module.php', "\$rates[\$i] = ['rate' => -\$slope, 'group' => \$row['module'] . '|' . (BWACHZelle::isKnown(\$row['cell']) ? \$row['cell'] : 'ohne Zelltyp')];", "\$rates[\$i] = ['rate' => -\$slope, 'group' => 'alle'];", 'Vergleich mischt Systeme und Zelltypen'],
    ['module.php', "return (is_int(\$val) || is_float(\$val)) && \$age <= 12 * 3600 ? (float)\$val : null;", "return (is_int(\$val) || is_float(\$val)) ? (float)\$val : null;", 'Veraltete Außentemperatur wird verwendet'],
    // --- 0.5.1: Geräteliste mit erkannten Geräten vorbelegt
    ['module.php', "if (\$id > 0 && isset(\$have[\$id])) {\n                    continue;", "if (false) {\n                    continue;", 'Doppelte gespeicherte Zeilen werden übernommen'],
    ['module.php', "if (\$id > 0 && !isset(\$have[\$id]) && IPS_InstanceExists(\$id)) {", "if (\$id > 0 && IPS_InstanceExists(\$id)) {", 'Bereits gespeicherte Geräte werden doppelt angelegt'],
    ['module.php', "if (\$id > 0 && !isset(\$have[\$id]) && IPS_InstanceExists(\$id)) {", "if (\$id > 0 && !isset(\$have[\$id])) {", 'Nicht vorhandene Instanzen werden angelegt'],
    ['module.php', "uasort(\$new, function (\$a, \$b) { return strcasecmp(\$a['Name'], \$b['Name']); });", "", 'Neue Zeilen unsortiert'],
    ['module.php', "'loadValuesFromConfiguration' => false,", "'loadValuesFromConfiguration' => true,", 'Liste ignoriert die eingesetzten Werte'],
    ['module.php', "'expanded' => \$dr['added'] > 0 || \$dr['filled'] > 0,", "'expanded' => false,", 'Panel mit neuen Zeilen bleibt zu'],
    ['module.php', "'Cell'      => \$cell,\n                    'Cells'     => max(1, min(12, (int)(\$r['Cells'] ?? 1))),\n                    'Poll'      => (bool)(\$r['Poll'] ?? false),\n                    'Alias'     => \$this->cleanAlias((string)(\$r['Alias'] ?? '')),\n                ];", "'Cell'      => BWACHZelle::UNKNOWN,\n                    'Cells'     => 1,\n                    'Poll'      => false,\n                    'Alias'     => '',\n                ];", 'Gespeicherter Zelltyp geht beim Öffnen verloren'],
    ['module.php', "'where'   => 'Instanz „' . IPS_GetName(\$this->InstanceID) . '“ öffnen, Panel „Geräte-Einstellungen“, Spalte „Zelltyp“',", "'where'   => '',", 'Hinweis nennt den Ort nicht'],
    // --- 0.5.2: CR123A-Batterie und RCR123A-Akku
    ['BWACHZelle.php', "in_array(\$id, ['cr123a', 'rcr123a'], true) ? 3 :", "in_array(\$id, ['cr123a', 'rcr123a'], true) ? 1 :", 'Vorschlag nennt keine CR123A in Reihe'],
    ['BWACHZelle.php', "'shop' => 'RCR123A (Akku)',", "'shop' => 'CR123A',", 'RCR123A-Akku wird als CR123A eingekauft'],
    ['BWACHLogik.php', "if (count(\$functionNames) === 1) {", "if (count(\$functionNames) >= 1) {", 'Matter-Name: bei mehreren Funktionsinstanzen zufällig die erste'],
    ['BWACHLogik.php', "'/\\s*Stromversorgung\\s*\$/iu'", "'/\\s*XStromversorgung\\s*\$/iu'", 'Matter-Name: Zusatz „Stromversorgung“ bleibt stehen'],
    ['BWACHLogik.php', "if (!isset(\$power[\$node])) {", "if (true) {", 'Matter-Hinweis nennt auch Knoten mit Endpunkt 0'],
    ['BWACHLogik.php', "\$i['endpoint'] < \$first[\$node][0]", "\$i['endpoint'] > \$first[\$node][0]", 'Matter-Hinweis: nicht die erste Funktionsinstanz'],
    ['module.php', "if (\$cell === BWACHZelle::UNKNOWN && (\$fromDev = \$this->cellFromDevice(\$id)) !== BWACHZelle::UNKNOWN) {", "if ((\$fromDev = \$this->cellFromDevice(\$id)) !== BWACHZelle::UNKNOWN) {", 'Geräteliste: gewählter Zelltyp wird mit dem Gerätewert überschrieben'],
    ['module.php', "'Excluded' => false, 'Cell' => \$cell, 'Cells' => 1, 'Poll' => false, 'Alias' => ''];", "'Excluded' => false, 'Cell' => BWACHZelle::UNKNOWN, 'Cells' => 1, 'Poll' => false, 'Alias' => ''];", 'Geräteliste: neue Zeilen ohne Zelltyp vom Gerät'],
    ['module.html', "if (missing(va) !== missing(vb)) { return missing(va) ? 1 : -1; }", "if (missing(va) !== missing(vb)) { return missing(va) ? -1 : 1; }", 'Sortierung: Geräte ohne Wert stehen vorn statt hinten'],
    ['module.html', "return c !== 0 ? sign * c : a.i - b.i;", "return c !== 0 ? c : a.i - b.i;", 'Sortierung: Richtung wird ignoriert'],
    ['module.html', "{ id: 'percent',  label: 'Batteriestand',  num: true,  dir: 'asc',", "{ id: 'percent',  label: 'Batteriestand',  num: true,  dir: 'desc',", 'Sortierung: Batteriestand beginnt mit dem höchsten'],
    ['module.html', "bwSort = { key: id, dir: bwSort.dir === 'asc' ? 'desc' : 'asc' };", "bwSort = { key: id, dir: bwSort.dir };", 'Sortierung: zweiter Klick kehrt nicht um'],
    ['module.php', "'cellKey'      => BWACHZelle::isKnown(\$row['cell']) ? (string)BWACHZelle::shopLabel(\$row['cell']) : '',", "'cellKey'      => '',", 'Kachel-Daten ohne Zelltyp-Kurzbezeichnung'],
    ['module.php', "'percent' => 'PercentSort',", "'percent' => 'Percent',", 'Liste: Sortierung nach Batteriestand vergleicht Text statt Zahl'],
    ['module.php', "'direction' => \$dir === 'descending' ? 'descending' : 'ascending',", "'direction' => 'ascending',", 'Liste: Richtung „absteigend“ wird ignoriert'],
    ['module.php', "'PercentSort'   => \$p === null ? 1000.0 : round(\$p, 1),", "'PercentSort'   => \$p === null ? -1.0 : round(\$p, 1),", 'Liste: Geräte ohne Batteriewert stehen vorn'],
    ['module.php', "\$v  = (float)\$sig['percent']['value'] * (float)(\$sig['percent']['scale'] ?? 1.0);", "\$v  = (float)\$sig['percent']['value'];", 'Liste: Matter-Halbprozent-Skala fehlt im angezeigten Batteriestand'],
    ['module.php', "\$this->UpdateFormField('DeviceSettings', 'sort', json_encode(\$this->sortSpec(\$By, \$Dir)));", "\$this->UpdateFormField('DeviceSettings', 'sort', json_encode(\$this->sortSpec('name', 'ascending')));", 'Liste: Umsortieren im offenen Formular ignoriert die Auswahl'],
    ['BWACHLogik.php', "if (array_key_exists('Active', \$rule) && !\$rule['Active']) {", "if (false) {", 'Regel: abgeschaltete Regel gilt trotzdem'],
    ['BWACHLogik.php', "if (\$part !== '' && mb_stripos(\$value, \$part) !== false) {", "if (mb_stripos(\$value, \$part) !== false) {", 'Regel: leeres Musterteil trifft alles'],
    ['BWACHLogik.php', "if (\$part !== '' && mb_stripos(\$value, \$part) !== false) {", "if (\$part !== '' && mb_strpos(\$value, \$part) !== false) {", 'Regel: Groß-/Kleinschreibung zählt'],
    ['BWACHLogik.php', "if (\$own['cell'] === BWACHZelle::UNKNOWN && BWACHZelle::isKnown((string)(\$r['Cell'] ?? ''))) {", "if (BWACHZelle::isKnown((string)(\$r['Cell'] ?? ''))) {", 'Regel überschreibt den eigenen Zelltyp'],
    ['BWACHLogik.php', "\$own['cells'] = max(1, min(12, (int)(\$r['Cells'] ?? 1)));", "", 'Regel: Zellenzahl wird nicht übernommen'],
    ['BWACHLogik.php', "if (!\$own['excluded'] && !empty(\$r['Excluded'])) {", "if (false) {", 'Regel „ausnehmen“ wirkt nicht'],
    ['BWACHLogik.php', "foreach (array_values(\$rules) as \$i => \$r) {\n            if (self::ruleMatches(\$r, \$dev)) {\n                return \$i;", "foreach (array_reverse(array_values(\$rules), true) as \$i => \$r) {\n            if (self::ruleMatches(\$r, \$dev)) {\n                return \$i;", 'Regel: die letzte statt der ersten passenden gilt'],
    ['module.php', "\$st = BWACHLogik::applyRules(", "\$st = (fn(\$a, \$b, \$c) => \$a)(", 'Auswertung ignoriert die Gruppen-Regeln'],
    ['module.php', "\$hits[\$i]++;", "", 'Regel-Treffer werden nicht gezählt'],
    ['module.php', "\$crit = \$this->ReadPropertyInteger('CriticalLowPercent');", "\$crit = 30;", 'Hilfetext: feste statt eingestellter Schwelle für „kritisch“'],
    ['module.php', "(\$quiet ? '; die Ruhezeit gilt dafür nicht' : '')", "'; die Ruhezeit gilt dafür nicht'", 'Hilfetext: Ruhezeit-Aussage auch wenn sie nicht gilt'],
    ['module.php', "älter als \$pAfter Tage, schickt der Wächter dem Gerät höchstens alle \$pEvery Tage", "älter als \$pEvery Tage, schickt der Wächter dem Gerät höchstens alle \$pAfter Tage", 'Hilfetext: Abfrage-Werte vertauscht'],
    ['module.php', "'caption' => 'Wie sicher ist die Prognose?', 'width' => '500px'", "'caption' => 'Wie sicher ist die Prognose, und was heißt „aus Spannung berechnet“?', 'width' => '500px'", 'Schaltfläche mit zu langer Beschriftung'],
    ['BWACHPrognose.php', "!preg_match('#^https?://#i', \$template)", "false", 'Linkvorlage: auch ohne http(s) gültig'],
    ['BWACHPrognose.php', "strpos(\$template, '{Zelltyp}') === false", "false", 'Linkvorlage: auch ohne {Zelltyp} gültig'],
    ['BWACHPrognose.php', "preg_match('/[\\s<>\"\\']/', \$template)", "false", 'Linkvorlage: Leer- und Sonderzeichen erlaubt'],
    ['BWACHPrognose.php', "mb_strlen(\$template) > 300", "false", 'Linkvorlage: beliebig lang'],
    ['BWACHPrognose.php', "str_replace('{Zelltyp}', rawurlencode(\$label), \$template)", "str_replace('{Zelltyp}', \$label, \$template)", 'Linkvorlage: Bezeichnung nicht URL-kodiert'],
    ['BWACHPrognose.php', "\$out[] = 'Zelltyp fehlt bei: ' . implode(', ', \$shopping['missing']);", "", 'Einkaufstext: fehlender Zelltyp fehlt'],
    ['BWACHPrognose.php', "if (\$round['count'] > 0) {", "if (false) {", 'Einkaufstext: Tauschrunde fehlt'],
    ['module.html', "if (it.url && /^https?:\\/\\//i.test(it.url)) {", "if (it.url) {", 'Kachel: Link auch bei javascript:-Adresse'],
    ['module.html', "a.rel = 'noopener noreferrer';", "", 'Kachel: Link ohne noopener'],
    ['module.html', "bs.onclick = function () { requestAction('shop_send', ''); };", "bs.onclick = function () { };", 'Kachel: „Senden“ tut nichts'],
    ['module.html', "var shownMsg = bwLocalMsg || BW.message;", "var shownMsg = BW.message;", 'Kachel: Rückmeldung von „Kopieren“ wird nicht gezeigt'],
    ['module.php', "\$channels = ['push' => \$this->ReadPropertyBoolean('NotifyPush'), 'mail' => \$this->ReadPropertyBoolean('NotifyMail')];", "\$channels = ['push' => \$this->ReadPropertyBoolean('NotifyPush') && \$this->ReadPropertyBoolean('NotificationsActive'), 'mail' => \$this->ReadPropertyBoolean('NotifyMail') && \$this->ReadPropertyBoolean('NotificationsActive')];", 'Einkaufsliste senden hängt an „Meldungen aktiv“'],
    ['module.php', "return \$ok > 0 ? '✅ Einkaufsliste gesendet'", "return true ? '✅ Einkaufsliste gesendet'", 'Einkaufsliste senden meldet immer Erfolg'],
    ['BWACHMeldung.php', "if (\$y < 2015 || !checkdate(\$mo, \$d, \$y)) {", "if (\$y < 2014 || !checkdate(\$mo, \$d, \$y)) {", 'Datum: Jahr 2014 wird akzeptiert'],
    ['BWACHMeldung.php', "if (\$y < 2015 || !checkdate(\$mo, \$d, \$y)) {", "if (\$y < 2015) {", 'Datum: 31.02. wird akzeptiert'],
    ['BWACHMeldung.php', "return \$t > \$now ? null : \$t;", "return \$t;", 'Datum: Zukunft wird akzeptiert'],
    ['BWACHMeldung.php', "(\$last === null || (int)\$e['t'] > \$last)", "(\$last === null || (int)\$e['t'] < \$last)", 'Letzter Wechsel: der älteste statt der jüngste'],
    ['BWACHMeldung.php', "if (\$months <= 0 || \$last === null) {", "if (\$last === null) {", 'Vorsorge: auch bei 0 Monaten'],
    ['BWACHMeldung.php', "return ['due' => \$since >= \$months, 'months' => round(\$since, 1)];", "return ['due' => \$since <= \$months, 'months' => round(\$since, 1)];", 'Vorsorge: fällig vor dem Intervall statt danach'],
    ['BWACHMeldung.php', "if (!empty(\$r['preventive'])) {\n            \$p[] = self::PROB_PREVENT;\n        }", "", 'Vorsorge löst keine Meldung aus'],
    ['BWACHMeldung.php', "} elseif (in_array(self::PROB_PREVENT, \$p, true) && !in_array(self::PROB_SOON, \$p, true)) {", "} elseif (false) {", 'Vorsorge-Meldung ohne eigenen Titel'],
    ['BWACHPrognose.php', "|| \$soon || !empty(\$i['preventive'])) {", "|| \$soon) {", 'Vorsorge: nicht in Tauschrunde und Einkauf'],
    ['BWACHPrognose.php', "if (\$have >= \$n) {", "if (\$have > \$n) {", 'Vorrat: genau passender Vorrat deckt nicht'],
    ['BWACHPrognose.php', "\$toBuy = \$n - \$have;", "\$toBuy = \$n;", 'Vorrat wird nicht abgezogen'],
    ['BWACHLogik.php', "return preg_match('/[;\"\\r\\n]/', \$c) ? '\"' . str_replace('\"', '\"\"', \$c) . '\"' : \$c;", "return \$c;", 'CSV: keine Anführungszeichen'],
    ['module.php', "if (\$st['critical'] && \$pm > 0) {", "if (\$pm > 0) {", 'Vorsorge gilt auch für unkritische Geräte'],
    ['module.php', "\$r['urgency']    = max(\$r['urgency'], 450);", "\$r['urgency']    = max(\$r['urgency'], 100);", 'Vorsorge ist kaum dringlich'],
    ['module.php', "if (count(\$new) === count(\$diary)) {", "if (false) {", 'Nachtragen: Doppeleintrag wird nicht erkannt'],
    ['module.php', "usort(\$new, function (\$a, \$b) { return (int)\$a['t'] <=> (int)\$b['t']; });", "", 'Nachtragen: Tagebuch bleibt unsortiert'],
    ['module.php', "\$out[\$label] = (\$out[\$label] ?? 0) + max(0, min(9999, (int)(\$r['Count'] ?? 0)));", "\$out[\$label] = max(0, min(9999, (int)(\$r['Count'] ?? 0)));", 'Vorrat: gleiche Bezeichnungen werden nicht summiert'],
    ['module.html', "if ((a === '') !== (b === '')) { return a === '' ? 1 : -1; }", "if ((a === '') !== (b === '')) { return a === '' ? -1 : 1; }", 'Nach Ort: „ohne Ort“ steht vorn'],
    ['module.html', "{ id: 'prevent',  label: '🗓 Vorsorge',      test: function (d) { return d.preventive; } },", "", 'Kachel: Filter „Vorsorge“ fehlt'],
    ['module.html', "bwGroup = !bwGroup;", "bwGroup = bwGroup;", 'Kachel: „Nach Ort“ lässt sich nicht umschalten'],
    ['module.php', "['Z-Wave Module' => 'ZW_RequestStatus', 'Matter Device' => 'MATTER_RequestStatus']", "['Z-Wave Module' => 'ZW_RequestStatus']", 'Abfrage: Matter wird nicht abgefragt'],
    ['module.php', "['Z-Wave Module' => 'ZW_RequestStatus', 'Matter Device' => 'MATTER_RequestStatus']", "['Z-Wave Module' => 'ZW_RequestStatus', 'Matter Device' => 'ZW_RequestStatus']", 'Abfrage: Matter ruft die Z-Wave-Funktion auf'],
    ['module.php', "'caption' => 'Abfragen (Z-Wave, Matter)'", "'caption' => 'Abfragen'", 'Spalte „Abfragen“ nennt die Systeme nicht'],
    ['BWACHPrognose.php', "\$slope >= 0 || !in_array(\$confidence, ['hoch', 'mittel'], true)", "\$slope >= 0", 'Prognose-Protokoll: auch bei geringer Sicherheit'],
    ['BWACHPrognose.php', "if (\$pct === null || \$slope === null || \$slope >= 0", "if (\$pct === null || \$slope === null || \$slope > 0", 'Prognose-Protokoll: auch ohne Entladung (Steigung 0)'],
    ['BWACHPrognose.php', "if (\$last !== null && \$now - (int)\$last['t'] < 7 * 86400) {", "if (false) {", 'Prognose-Protokoll: öfter als einmal pro Woche'],
    ['BWACHPrognose.php', "return array_slice(\$log, -self::ACC_LOG_MAX);", "return \$log;", 'Prognose-Protokoll: wächst unbegrenzt'],
    ['BWACHPrognose.php', "if (\$age >= self::ACC_MIN_AGE_DAYS && \$age <= self::ACC_MAX_AGE_DAYS) {", "if (\$age <= self::ACC_MAX_AGE_DAYS) {", 'Prognose-Vergleich: auch zu junge Prognosen'],
    ['BWACHPrognose.php', "if (\$age >= self::ACC_MIN_AGE_DAYS && \$age <= self::ACC_MAX_AGE_DAYS) {", "if (\$age >= self::ACC_MIN_AGE_DAYS) {", 'Prognose-Vergleich: auch zu alte Prognosen'],
    ['BWACHPrognose.php', "round(\$actualPct - \$pred, 1)", "round(\$pred - \$actualPct, 1)", 'Prognose-Vergleich: Vorzeichen der Abweichung vertauscht'],
    ['BWACHPrognose.php', "max(0.0, min(100.0, (float)\$e['p'] + (float)\$e['s'] * \$age))", "(float)\$e['p'] + (float)\$e['s'] * \$age", 'Prognose-Vergleich: Prozent nicht begrenzt'],
    ['BWACHPrognose.php', "array_sum(array_map('abs', \$errs)) / count(\$errs)", "array_sum(\$errs) / count(\$errs)", 'Genauigkeit: mittlere Abweichung ohne Betrag'],
    ['BWACHLogik.php', "'done' => \$dev > 0 && \$open === 0,", "'done' => \$dev > 0,", 'Erste Schritte: Zelltypen gelten als erledigt, obwohl welche fehlen'],
    ['BWACHLogik.php', "\$notified = !empty(\$s['notify']) && !empty(\$s['channel']);", "\$notified = !empty(\$s['notify']);", 'Erste Schritte: Meldungen ohne Zustellweg gelten als erledigt'],
    ['BWACHLogik.php', "if (preg_match('/(batt|\\bbat\\b|lowbat|low_bat|akku|battery)/i', (string)\$v['ident'] . ' ' . (string)\$v['name'])) {", "if (false) {", 'Diagnose: nicht erkannte batterieähnliche Variablen fehlen'],
    ['BWACHLogik.php', "if (isset(\$known[(int)\$v['vid']])) {\n                continue;\n            }", "", 'Diagnose: erkannte Variablen stehen auch unter „nicht erkannt“'],
    ['BWACHLogik.php', "if (!\$own['poll'] && !empty(\$r['Poll'])) {", "if (false) {", 'Regel kann „Abfragen“ nicht einschalten'],
    ['module.php', "\$byLife = (\$state[\$key]['why'] ?? 'alt') === 'still' && (int)\$row['life'] > \$t;", "\$byLife = (int)\$row['life'] > \$t;", 'Abfrage: jedes Lebenszeichen gilt auch bei einer Anfrage wegen alten Werts'],
    ['module.php', "'Matter Device' => 6 * 3600]", "'Matter Device' => 14 * 86400]", 'Abfrage: Matter wartet 14 Tage statt 6 Stunden'],
    ['module.php', "if (!\$row['pollOn'] || \$fn === null || (!\$old && !\$still)) {", "if (!\$row['pollOn'] || \$fn === null || !\$old) {", 'Abfrage bei Funkstille fehlt'],
    ['module.php', "'why' => \$still && !\$old ? 'still' : 'alt']", "'why' => 'alt']", 'Abfrage: Anlass wird nicht festgehalten'],
    ['module.php', "\$devs  = \$v['round']['places'][\$place] ?? [];", "\$devs  = [];", 'Alle getauscht: findet keine Geräte'],
    ['module.php', "\$this->ackApply((string)\$d['id'], BWACHMeldung::ACK_REPLACED, (string)\$d['name']);", "", 'Alle getauscht: trägt nichts ein'],
    ['module.php', "\$entry['acc'] = \$acc;", "", 'Tagebuch ohne Prognose-Vergleich'],
    ['module.php', "unset(\$fc[\$key]);\n                \$fcChanged = true;", "\$fcChanged = true;", 'Prognose-Protokoll bleibt nach dem Wechsel stehen'],
    ['module.html', "if (!sure) { bwSure = 'place:' + p.place; bwRender(); return; }", "", 'Kachel: „Alles getauscht“ ohne Rückfrage'],
    ['BWACHLogik.php', "if (empty(\$v['parentIsInstance']) || (string)\$v['ident'] === '' || in_array(mb_strtolower((string)\$v['moduleName']), \$excludedModules, true)) {", "if ((string)\$v['ident'] === '' || in_array(mb_strtolower((string)\$v['moduleName']), \$excludedModules, true)) {", 'Diagnose: Skriptvariablen stehen unter „nicht erkannt“'],
    ['BWACHLogik.php', "if (empty(\$v['parentIsInstance']) || (string)\$v['ident'] === '' || in_array(mb_strtolower((string)\$v['moduleName']), \$excludedModules, true)) {", "if (empty(\$v['parentIsInstance']) || in_array(mb_strtolower((string)\$v['moduleName']), \$excludedModules, true)) {", 'Diagnose: Variablen ohne Ident stehen unter „nicht erkannt“'],
    ['BWACHLogik.php', "if (empty(\$v['parentIsInstance']) || (string)\$v['ident'] === '' || in_array(mb_strtolower((string)\$v['moduleName']), \$excludedModules, true)) {", "if (empty(\$v['parentIsInstance']) || (string)\$v['ident'] === '') {", 'Diagnose: Ausschlussliste gilt nicht'],
    ['module.php', "\$kernel, \$this->excludedModules());", "\$kernel);", 'Diagnose im Modul kennt die Ausschlussliste nicht'],
    ['module.php', "bis du „Meldungen aktiv“ einschaltest.", "bis Sie „Meldungen aktiv“ einschalten.", 'Förmliche Anrede im Meldungen-Hinweis'],
    ['module.php', "\$cut = count(\$pending) > 3;", "\$cut = false;", '„Neu“ zeigt die ganze Entwicklungsgeschichte'],
    ['module.php', "\$pending = array_slice(\$pending, -3, 3, true);", "\$pending = array_slice(\$pending, 0, 3, true);", '„Neu“ zeigt die ältesten statt der neuesten drei Versionen'],
    ['module.php', "if (\$info['effectiveCell'] === BWACHZelle::UNKNOWN && !\$info['effectiveExcluded'] && \$id > 0 && IPS_InstanceExists(\$id)) { \$open[] = \$info['Name']; }", "if (\$info['effectiveCell'] === BWACHZelle::UNKNOWN && \$id > 0 && IPS_InstanceExists(\$id)) { \$open[] = \$info['Name']; }", 'Ausgenommene Geräte zählen als „ohne Zelltyp“ (gespeicherte Zeile)'],
    ['module.php', "'effectiveExcluded' => (bool)\$eff['excluded'],", "'effectiveExcluded' => false,", 'Ausgenommene Geräte zählen als „ohne Zelltyp“ (per Regel)'],
    ['module.php', "\$ok    = \$this->deliver('🛒 Batterien einkaufen', \$parts[1] ?? \$parts[0], 'bell', \$channels);", "\$ok    = \$this->deliver('🛒 Batterien einkaufen', \$this->ShoppingText(), 'bell', \$channels);", 'Einkaufsliste senden: Überschrift doppelt'],
    ['module.php', "/144608';", "/144609';", 'Rückmeldungen: falsche Thread-URL'],
    ['module.php', "['type' => 'Button', 'caption' => 'Zum Forum-Thread', 'onClick' => \"echo '\" . self::FORUM_URL . \"';\", 'link' => true],", "", 'Rückmeldungen: Forum-Schaltfläche fehlt'],
    ['module.php', "if (\$this->ReadAttributeString('ForumHintSeen') === self::FORUM_HINT_REV) {", "if (\$this->ReadAttributeBoolean('ForumHintGone')) {", 'Rückmeldungen-Hinweis bleibt für alle weg, die einen alten weggeklickt haben'],
    ['module.php', "\$this->WriteAttributeString('ForumHintSeen', self::FORUM_HINT_REV);", "\$this->WriteAttributeString('ForumHintSeen', '');", 'Rückmeldungen-Hinweis lässt sich nicht wegklicken'],
    ['module.php', "['type' => 'Button', 'caption' => '💬 Forum-Thread',", "['type' => 'Label', 'caption' => '💬 Forum-Thread',", 'Forum-Link in der Dokumentation fehlt'],
    ['module.php', "Die Sortierung gilt nach „Änderungen übernehmen“:", "Die Sortierung gilt sofort:", 'Sortier-Hinweis sagt, die Sortierung gelte sofort'],
    ['BWACHLogik.php', "if (count(\$keys) < 2) {\n                continue;\n            }\n            sort(\$keys);", "if (false) {\n                continue;\n            }\n            sort(\$keys);", 'HomeMatic: Kanäle werden auch einzeln „zusammengefasst“'],
    ['BWACHLogik.php', "if ((\$devices[\$k]['chan'] ?? '') !== '0') {", "if (true) {", 'HomeMatic: Hauptinstanz ist auch der Wartungskanal'],
    ['BWACHLogik.php', "\$devices[\$primary]['signals'][\$kind][] = \$sg;", "", 'HomeMatic: Signale des zweiten Kanals gehen verloren'],
    ['BWACHLogik.php', "if (count(\$list) < 2 || !empty(\$d['merged'])) {", "if (count(\$list) < 2) {", 'HomeMatic: zusammengeführte Flags werden wieder aufgeteilt'],
    ['BWACHLogik.php', "if ((\$d['group'] ?? '') !== '' && is_int(\$key)) {", "if (is_int(\$key)) {", 'HomeMatic: Geräte ohne Gruppe werden zusammengefasst'],
    ['module.php', "if (stripos(\$module, 'homematic') === false) {", "if (false) {", 'HomeMatic: jedes Modul mit Adresse „x:n“ wird zusammengefasst'],
    ['module.php', "if ((int)\$mb !== \$id && IPS_InstanceExists((int)\$mb)) {\n                    \$life = max(\$life, \$this->lifeSign((int)\$mb, true, []));\n                }", "", 'HomeMatic: Lebenszeichen der anderen Kanäle zählt nicht'],
    ['module.php', "\$name = isset(\$d['parent']) ? \$alias . mb_substr(\$name, mb_strlen(\$label['name'])) : \$alias;", "", 'Anzeigename wird nicht verwendet'],
    ['module.php', "'alias'     => \$this->cleanAlias((string)(\$r['Alias'] ?? '')),", "'alias'     => '',", 'Anzeigename wird beim Auswerten ignoriert'],
    ['module.php', "return mb_substr(\$s, 0, 60);", "return \$s;", 'Anzeigename wird nicht gekürzt'],
    ['module.php', "(string)preg_replace('/[\\x00-\\x1F\\x7F]+/u', ' ', \$s)", "(string)\$s", 'Anzeigename mit Zeilenumbruch bleibt'],
    ['module.html', "if (q !== '') {\n                shown = shown.filter(", "if (false) {\n                shown = shown.filter(", 'Suchfeld filtert nicht'],
    ['module.html', ".toLowerCase().indexOf(q) >= 0;", ".indexOf(q) >= 0;", 'Suche achtet auf Groß-/Kleinschreibung'],
    ['module.html', "String(d.place || '') + ' ' + String(d.module || '')", "''", 'Suche trifft nur den Namen, nicht Ort und System'],
    ['BWACHZelle.php', "'CR123A' => 'cr123a', 'RCR123A' => 'rcr123a'", "'CR123A' => 'rcr123a', 'RCR123A' => 'cr123a'", 'Gerätebeschreibung: CR123A und RCR123A vertauscht'],
    ['BWACHZelle.php', "'AA' => 'aa_alkali', 'AAA' => 'aaa_alkali'", "'AA' => 'aaa_alkali', 'AAA' => 'aa_alkali'", 'Gerätebeschreibung: AA und AAA vertauscht'],
    ['BWACHLogik.php', "preg_match('/(^|_)batreplacementneeded\$/i', \$ident)", "preg_match('/(^|_)batreplacementneededX\$/i', \$ident)", 'Matter „Ersatz erforderlich“ nicht erkannt'],
    ['module.php', "\$o !== null && \$o['node'] === \$m['node'] && \$o['endpoint'] > 0", "\$o !== null && \$o['endpoint'] > 0", 'Matter: Instanzen anderer Knoten gelten als zugehörig'],
    ['module.php', "\$life = max(\$life, \$this->lifeSign(\$sb, true, []));", "\$life = \$life;", 'Matter: Lebenszeichen des Kontakts wird nicht berücksichtigt'],
    ['module.php', "\$name = BWACHLogik::matterDeviceName(IPS_GetName(\$id), array_map('IPS_GetName', \$sibs));", "\$name = IPS_GetName(\$id);", 'Matter: Name der Stromversorgung statt des Geräts'],
    ['module.php', "if (\$st['cell'] === BWACHZelle::UNKNOWN && \$cellHint !== '') {", "if (\$cellHint !== '') {", 'Gerätebeschreibung überschreibt den gewählten Zelltyp'],
    ['module.php', "\$sig['voltage'] = ['value' => \$volt > 100 ? \$volt / 1000 : \$volt, 'updated' => \$upd];", "\$sig['voltage'] = ['value' => \$volt, 'updated' => \$upd];", 'Millivolt werden als Volt gelesen'],
    ['module.php', '$this->SetTimerInterval(\'Debounce\', self::DEBOUNCE_MS);', '', 'Sammelfenster wird nie gestartet'],
    ['module.php', '$this->UnregisterMessage($sender, self::VM_UPDATE_MSG);', '', 'Abmeldung weggefallener Variablen entfällt'],
    ['module.php', 'htmlspecialchars((string)$s, ENT_QUOTES | ENT_SUBSTITUTE, \'UTF-8\')', '(string)$s', 'HTML-Maskierung entfällt'],
    ['module.php', "foreach (['VariableCustomPresentation', 'VariablePresentation'] as \$key)", 'foreach ([] as $key)', 'Darstellungs-Profil wird nie gelesen'],
    ['module.php', 'if ($st[\'excluded\'] ||', 'if (false ||', 'Ausnehmen wirkungslos'],
    ['module.php', '> self::REDISCOVER_SEC', '> 99999999', 'tägliche Neusuche entfällt'],
    ['module.php', '$max = max($max, (int)($var[\'VariableUpdated\'] ?? 0));', '', 'Lebenszeichen immer 0'],
    ['module.php', "\$this->UpdateFormField('CheckStatus', 'caption', \$line);", '', 'Zustandszeile wird nicht aufgefrischt'],
    ['module.php', "\$this->UpdateFormField('DiscoveryStatus', 'caption', \$line);", '', 'Kopfzeile wird nicht aufgefrischt'],
    ['module.php', "\$this->WriteAttributeString('SeenNews', \$this->installedVersion());", '', '„Verstanden“ speichert nichts'],
];

$tmpBase = sys_get_temp_dir() . '/bwach-mut-' . getmypid();
@mkdir($tmpBase);
$survivors = [];
$killed = 0;
$skipped = 0;

foreach ($mutations as [$file, $search, $replace, $desc]) {
    $code = file_get_contents($src . '/' . $file);
    if (strpos($code, $search) === false) { $skipped++; echo "  ⏭  nicht anwendbar: $desc\n"; continue; }   // Variante trifft nicht zu (z. B. andere Anführungszeichen)
    $dir = $tmpBase . '/m';
    @mkdir($dir);
    foreach (glob($src . '/*') as $f) { copy($f, $dir . '/' . basename($f)); }
    file_put_contents($dir . '/' . $file, str_replace($search, $replace, $code));
    $out = [];
    exec('BWACH_MODULE_DIR=' . escapeshellarg($dir) . ' php ' . escapeshellarg($root . '/.tools/test-bwach.php') . ' 2>&1', $out, $rc);
    foreach (glob($dir . '/*') as $f) { unlink($f); }
    @rmdir($dir);
    if ($rc !== 0) { $killed++; echo "  ☠️  getötet:   $desc\n"; }
    else { $survivors[] = $desc; echo "  🧟 ÜBERLEBT:  $desc\n"; }
}
@rmdir($tmpBase);

echo "\n$killed getötet, " . count($survivors) . " überlebt, $skipped nicht anwendbar.\n";
exit(count($survivors) === 0 ? 0 : 1);
